### ISSUE TITLE
[BUG] Incorrect example

### ISSUE THREAD

**Issue by gigantino** [mathieucarbou/MycilaJSY#6]
**Firmware**

9.1.6

**Description**

The example that can be found in the additional notes returns the following error:
`class "Mycila::JSY" has no member "toJson"C/C++(135)`

**Board**

esp32dev

**Additional notes**

https://github.com/mathieucarbou/MycilaJSY/blob/main/examples/Read/Read.ino#L34

**Comment by mathieucarbou** [comment]
Please read the doc and look at the PlatformIO file.
https://github.com/mathieucarbou/MycilaJSY?tab=readme-ov-file#json-support
